### ISSUE TITLE
Juvix release source archives do not contain juvix-stdlib

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#1430]
The Juvix release source archives (e.g at https://github.com/anoma/juvix/archive/refs/tags/v0.2.2.tar.gz) do not contain the juvix-stdlib code and so cannot be used to build the project.

This is an issue when using these archives for distribution (e.g homebrew formula).

```shell
$ wget https://github.com/anoma/juvix/archive/refs/tags/v0.2.2.tar.gz
$ tar xf v0.2.2.tar.gz
$ tree juvix-0.2.2/juvix-stdlib
juvix-0.2.2/juvix-stdlib

0 directories, 0 files
```

Note: This happens because the juvix-stdlib is a git submodule.

**Comment by jonaprieto** [comment]
We should start crafting each release manually instead of using the Github web browser interface. The plan is to use the Github CLI tool (`gh release`) that allows us to add all we want to ship in the release. 

## Checklist

- [ ] Add `make release` for automating all the release process:
   - [ ] The title of the release is the numeric version of the juvix binary:
     - [ ] Implement a new flag `--numeric version` to be used when calling `gh`: `VERSION=juvix --numeric-version`
     - [ ] Bump the version automatically in the `package.yaml`
     - [ ] Create the corresponding tag with the new version: `git tag v$(VERSION)`
   - [ ] Create the tar ball files:
      - [ ] Run `make ci` to make sure everything is working as expected before packing all
      - [ ] Check the expected folder and files exist
