### ISSUE TITLE
Respect user's spacing decisions in the formatter

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#1837]
Where spaces are not required in the syntax and the user didn't put them in, they generally should not be added.

For example, we should respect the user's decisions about spaces before `,` and after `\` and `λ`. For someone not coming from the Agda world, it is super annoying that spaces get automatically inserted there, especially with the comma. In terms of annoyance, it's as if we were automatically inserting a space after every `(`.

**Comment by janmasrovira** [comment]
- About `,`. Imo the formatter should be opinionated and not respect the spaces of the user, instead, it should always have spaces before `,` or never. Since we have the special rule for `,` I would say the best is to never have spaces before it. I.e. `a , b` will be formatted to `a, b`. Implementation wise,  `,` is currently treated as a normal infix operator, which makes the implementation elegant. I'll need to see how hard it is to incororate this change.
- About `\` and `λ` I also think the formatter should be opinionated and not respect the spaces that the user wrote. Imo it looks much nicer with a space after the lambda: `λ {x := x}` looks better than `λ{x := x}`, but this is subjective. In any way, we should probably decide one way or another as I would be disapointed if I found inconsistent spacing of `λ` after I run the formatter in a file.

**Comment by lukaszcz** [comment]
> * About `,`. Imo the formatter should be opinionated and not respect the spaces of the user, instead, it should always have spaces before `,` or never. Since we have the special rule for `,` I would say the best is to never have spaces before it. I.e. `a , b` will be formatted to `a, b`. Implementation wise,  `,` is currently treated as a normal infix operator, which makes the implementation elegant. I'll need to see how hard it is to incororate this change.
> 

If we're to be opinionated, I'd argue the format it to `a, b`, simply because it's the default convention with the comma used almost everywhere.

>     * About `\` and `λ` I also think the formatter should be opinionated and not respect the spaces that the user wrote. Imo it looks much nicer with a space after the lambda: `λ {x := x}` looks better than `λ{x := x}`, but this is subjective. In any way, we should probably decide one way or another as I would be disapointed if I found inconsistent spacing of `λ` after I run the formatter in a file.

I have exactly the opposite opinion on what looks "nicer", but I won't insist so much here because I don't think there exists an established general convention in this case.

**Comment by lukaszcz** [comment]
One way of not forcing your opinions would be to have options to the formatter which control whether the spaces should be inserted or removed in these cases. Then the users can have their own conventions, but the formatter still helps them to keep it consistent.

**Comment by janmasrovira** [comment]
We decided:
1. There should be no space before `,` when possible.
2. There will always be a space between `λ` and `{`.
3. There will not be any configuration option.
