### ISSUE TITLE
Possible bug in match to case + remove type args transformation

### ISSUE THREAD

**Issue by janmasrovira** [anoma/juvix#1867]
Consider this core file:
```
type Box {
    mkBox : Π A : Type, A → Box A;
};

def unbox : int -> int :=
    λ(n : int)
    match (mkBox int 1 : Box int) with : int {
        mkBox _ _ := n
    };
unbox 44
```

Running `juvix dev core read -t match-to-case,remove-type-args test054.jvc --eval` results in a crash in the evaluator

**Comment by paulcadman** [comment]
This is probably because `remove-type-args` assumes that all binders have (non-dynamic) type information? I think this because `juvix dev core read -t match-to-case test054.jvc --eval` doesn't crash.

I'm currently working on preserving the type information in `match-to-case` so hopefully this will fix the issue.

**Comment by lukaszcz** [comment]
It doesn't work because neither the number of inductive type parameters nor the types of binders in the `match` are set correctly. It works if you change this to:
```
type Box {
    mkBox : Π A : Type, A → Box A;
};

def unbox : int -> int :=
    λ(n : int)
    match (mkBox int 1 : Box int) with : int {
        mkBox (A : Type) _ := n
    };
unbox 44
```

What I'm doing in RemoveTypeArgs is technically under the assumption that all type information and parameter number information is provided. But maybe I should change this to rely on the type of the constructor instead? That would be less confusing when writing JuvixCore programs directly.

**Comment by janmasrovira** [comment]
I don't see why this is marked as completed. 

> It doesn't work because neither the number of inductive type parameters nor the types of binders in the match are set correctly

The only change I've noticed is that you added the type annotation `(A : Type)` in the pattern, but if I run `juvix dev core read -t match-to-case test054.jvc` I still get `mkBox _ _`. I don't think this should happen as it will create more confusion in the future

**Comment by lukaszcz** [comment]
Okay, I can change this to use the constructor type. But the bigger problem is that a JuvixCore program without complete type information is just not suited to be used with all the transformations. We can "fix" the problem of not having type information in `case` binders by assuming we have it in the constructor type, or we have the number of parameters (the second is what I assumed and it's true if you translate from Core).

**Comment by janmasrovira** [comment]
If type information is the only issue here, It should be fixed when @paulcadman refines the current `match-to-case` transformation so that it keeps type information. Then there is not need to change assumptions in `remove-type-args`.

**Comment by lukaszcz** [comment]
The point is that if you don't provide the type information in the match binders (or wildcards) in JuvixCore source, then `match-to-case` has nothing to preserve. And it's very easy to forget annotating the `match` and `case` binders, and it works as long as they don't bind type. It didn't work because you didn't annotate the first binder of the `match`. Currently, it seems `match-to-case` preserves some binder type information, but not completely correctly w.r.t. de Bruijn indices.

**Comment by janmasrovira** [comment]
I think that what confused me is that the prettyprinter does not print type annotations. If you have `(A : Type)` in the code, it will print `A`, so the user cannot assume that what's printed can be parsed into the original ast

**Comment by lukaszcz** [comment]
> I think that what confused me is that the prettyprinter does not print type annotations. If you have `(A : Type)` in the code, it will print `A`. Consequently, the user cannot assume that what's printed can be parsed into the original ast. We should fix that

Oh, it should print them if they're not Dynamic. That's a bug.

**Comment by lukaszcz** [comment]
But that's also a bigger problem: #1841
