### ISSUE TITLE
Add module encapsulation

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#1996]
Currently all definitions are exported from a module. We should add a method of encapsulation to modules In order for module authors to hide implementation details from users that import the module.

One option is to add `private` modifier that can be added to definitions at the top level of a module. Such definitions would not be visible other modules that import it.

```
module foo;

private f : Bar
f := ...
```

## Questions

1. Should private definitions be visible in nested modules?
2. Should we adopt an alternative approach?

**Comment by janmasrovira** [comment]
In today's meeting we touched on this topic. The notion of `protected` visibility has been brought into discussion.
The proposal is as follows.

A definition declared as `protected` is inherited in nested modules. However, it is not imported by default. Instead some explicit command is required. E.g.
```
module Lib;
  axiom Pub : Type;
  protected axiom Prot : Type;
end;
```
And then in another file:
```
module Main;
 import Lib open;
 -- Only `Pub` is in scope.

 open Lib using {protected Prot};
 -- Now `Prot` is also in scope.
 
 -- alternative syntax
 open Lib using protected {Prot};
```

About the syntax. We can call it `protected`, `internal` or something else. Then, in order to open a module, I propose two alternatives:
1. `open Lib using {[protected]  p1; ..; [protected]  pn};` Note that `[protected]` means optional.
2. `open Lib using protected {p1; ..; pn};`

Considerations about 1. 
1. We can mix `protected` and regular (public) symbols in the same statement. E.g. `using {protected gcd'; gcd}`. This can be seen as either an advantage or a disadvantage. I'd say is more of an advantage. Also, 
2. We always have the `protected` keyword next to the identifier. I'd say thi is a good thing.
3.  The syntax is very easy to remember.

Considerations about 2.
1. Less verbose if the list of symbols is long. I'd say that in practice the user will import very few protected symbols, so this is mostly irrelevant.
2. Should we be able to say `open Lib using protected {p1; ..; pn} public {a1; ..; an}` in order  to mix `protected` and `public` symbols? Or should we only allow to have `protected` symbols? The advantage of allowing mixing protected and public is that we allow more concise statements. The disadvantage is that the syntax gets more involved.


An open question: How would qualified protected symbols work? One option is to not allow the user to access protected symbols without an explicit `open` statement. But there may be better alternatives.

Both the syntax and whether having this is worth it is up to debate.

**Comment by lukaszcz** [comment]
I don't think protected stuff should be visible in any way unless explicitly indicated. The idea is to have a similar mechanism to protected fields in OOP.

So we might want something like
```
import protected Lib;
```
which would bring qualified protected symbols into scope.

Then
```
import protected Lib open;
```
would also bring unqualified protected symbols into scope?

It should never be possible to re-export an imported protected symbol as public (one can always get around such a restriction by using a public synonym definition, but the language should discourage this pattern).

**Comment by lukaszcz** [comment]
Perhaps without `import protected` one shouldn't even be able to open protected symbols at all. The idea is that by `import protected` we're indicating that the current module is an extension of the imported library. We want to provide for a use-case when one writes a separate module to extend a library. We want to discourage random usage of protected identifiers in other modules. The danger with adding `protected` on a by-identifier basis in an `open` statement is that people might start overusing it more easily, in comparison to a situation where we have different way of importing entire modules that we want to extend.

Perhaps it would be even better to use `inherit` instead of `import protected` to indicate that we're dealing with something essentially different from an ordinary module import, that we're actually extending the functionality of an existing module/library.

**Comment by lukaszcz** [comment]
I think that's similar to why OO languages don't just allow to change the visibility of protected methods to public locally on a per-method basis from unrelated classes -- you need to inherit the class. You want to provide for a certain pattern (extending an existing implementation) and make your language fit that pattern and discourage the use of the added features outside of this pattern. Of course, if the programmer isn't familiar with the pattern, they can always do some silly stuff, like making everything public. One should limit the possibility of people doing silly stuff with features whose purpose they don't understand, though I don't think this possibility can be entirely eliminated.

**Comment by lukaszcz** [comment]
Perhaps the `inherit` statement should behave similarly to OCaml's `include` (https://cs3110.github.io/textbook/chapters/modules/includes.html): it is as if we "pasted in" the code from the inherited module, except that `private` definitions are hidden.

I think we're touching here on the design of the module system, and the limitations of Haskell modules become apparent in this use-case.

Related issue:
* #1792

**Comment by paulcadman** [comment]
We can simulate private visibility with a combination of local modules and naming conventions. We're happy with this for now.
