### ISSUE TITLE
Unexpected error internal to core error with type aliases: undeclared identifier

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#2056]
Related to:
- #2055 
- https://github.com/anoma/juvix/pull/2040
- #2005

```agda
module E10;

type T0 (A : Type) :=
  | t : (A -> T0 A) -> T0 A;

axiom alias : Type -> Type;

type T1 :=
  | c : alias T1 -> T1;
```

I'm getting this error:

```
juvix: internal to core: undeclared identifier: alias
CallStack (from HasCallStack):
  error, called at src/Juvix/Prelude/Base.hs:342:9 in juvix-0.3.2-LpHIe68kEcQ6DZIdmT4nNv:Juvix.Prelude.Base
  error, called at src/Juvix/Compiler/Core/Translation/FromInternal.hs:799:20 in juvix-0.3.2-LpHIe68kEcQ6DZIdmT4nNv:Juvix.Compiler.Core.Translation.FromInternal 
```

**Comment by janmasrovira** [comment]
This is related to axioms, not type aliases.

The problem is that in the translation from Internal to Core we only handle axioms that are builtins. If during the translation we find a non-builtin axiom, we crash. This needs to be handled differently. One solution is to add axioms to Core and to add a pass (after typechecking and coverage checking) that checks that there are no axioms.

```
module example;

type Unit := unit : Unit;

axiom Boom : Unit;

x : Unit;
x := Boom;
```

**Comment by jonaprieto** [comment]
Once this issues is fixed, update:

- examples/milestone/Bank/Bank.juvix
