### ISSUE TITLE
 Refactor Keywords `terminating` and `positive` to Leverage Pragma Capability

### ISSUE THREAD

**Issue by jonaprieto** [anoma/juvix#2095]
Remove the `terminating` and `positive` keywords. Instead, we can consider using pragma statements such as:

1. `{-# attributes: terminating #-}` or 
2. `{-# terminating: true #-}`.

Feel free to propose an alternative. I believe the first suggestion offers more flexibility, but the second one aligns more closely with the pragma syntax used for inlining, i.e., `{-# inline true #-}`.

**Comment by lukaszcz** [comment]
I don't know what the syntax should be, but the disadvantage of `{-# terminating: true #-}` is that `{-# terminating: false #-}` doesn't make sense, in contrast to `{-# inline: false #-}`. But maybe `{-# terminating: true #-}` is still better than inventing some different syntax, so that things are consistent.

**Comment by mariari** [comment]
If you have record syntax, just reuse that with a word like declare/declaim. This only reserves 1 word, works with the current syntax, does not use a completely different grammar (I believe `{-# #-}` uses yaml, which is not juvix)  and does not include the awkward to write `{-#`. Further, depending on how the project evolves, this has a higher likelihood of being converted into a normal language construct, rather than being special when compared to `{-#` 


```haskell
declare ^ {
  inline: true;
  terminating: true;
  infix: infixr 5;
};


foo : String -> Stirng;
foo := identity;

^ : Int -> Int;
^ x y := exponent x y;
```

**Comment by lukaszcz** [comment]
I don't think we want to have `terminating` and `positive` as pragmas, because pragmas are supposed to not affect the semantics of the program. That's why they're a special kind of comments. It should be possible to remove all pragmas without breaking code. The pragmas are also supposed to be backward-compatible, so unknown pragmas are simply ignored.

But we might want to invent some general non-pragma yaml-based attributes, e.g.:
```
attribs fun {terminating: true};
```

Or maybe we just unify pragmas with attributes and not care about the distinction?

**Comment by jonaprieto** [comment]
We agreed to not have this.
