### ISSUE TITLE
Succinct syntax for type variable quantification

### ISSUE THREAD

**Issue by lukaszcz** [anoma/juvix#2148]
Now we always have to spell out the type variables explicitly:
```
f : {A B : Type} -> List A -> List B;
```
This is a lot of pointless typing, because a free variable in a type can only be a type variable (even with dependent types or type constructor variables this is the most common case and a reasonable default).

Most mainstream functional languages allow to omit the initial quantification over types:
```
f : List A -> List B;
```
Even in Coq one can do this (by using the backtick ` before the subtype whose free variables should be generalised). In practice, it becomes very tedious, especially with (dependent) traits/type classes, to explicitly list the types of all variables when those can be inferred from their usage.

I propose to consider automatically generalising over type variables in types: any free variables in a type are inferred to be implicitly quantified type variables and added at the front.

**Comment by janmasrovira** [comment]
If we were to do this, I'd prefer to take the Agda/Lean approach (I'm not sure what Idris does in this area):
1. https://leanprover.github.io/reference/other_commands.html#universes-and-variables
2. https://agda.readthedocs.io/en/v2.6.3/language/generalization-of-declared-variables.html#overview

So we would have something like
```
variable A : Type;
variable B : Type;

f : List A -> List B;
```

I think that forcing an explicit declaration of variables is a good idea because:
1. You don't need to commit to a single default, e.g. `Type`. Instead, we will have a generic system. This will be specially important as the type system grows and we will have more implicit arguments of type other than `Type`.
2. I feel like generalizing over all free variables is a bad idea. If you misspell an identifier in a type, it will be implicitly generalized to an implicit type variable, and that will lead to unexpected arity/type errors. Instead, if you get a scoping error, you are much more likely to solve the problem immediately.
4. By having an explicit declaration, it is _less magic_. The user can jump to the declaration of the variable and see its type there.

**Comment by lukaszcz** [comment]
> 1. You don't need to commit to a single default, e.g. `Type`. Instead, we will have a generic system. This will be specially important as the type system grows and we will have more implicit arguments of type other than `Type`.

It's easiest to implement but it's not necessary to have a default -- one can infer the type of a free variable from how it is used.

> 2. I feel like generalizing over all free variables is a bad idea. If you misspell an identifier in a type, it will be implicitly generalized to an implicit type variable, and that will lead to unexpected arity/type errors. Instead, if you get a scoping error, you are much more likely to solve the problem immediately.

I agree with this one and consider this a major argument against implicit generalisation.

> 3. By having an explicit declaration, it is _less magic_. The user can jump to the declaration of the variable and see its type there.

True, but I don't think this matters that much (as long as you don't have dependent types), because all free variables are type variables.

A third option is to have something like Coq where you explicitly indicate parts of the type in which the free variables should be generalised. Initially, Coq didn't have that, but they introduced it at some point because writing the type variables in all circumstances started getting really tedious in practice. For example,
```
sort : `{{Ord A}} -> List A -> List A;
```
would generalise the `A` because it's inside a backtick. In practice, the backticks are used mostly with type classes, because when you write a type class over a type, then, well, it's doubly obvious that `A` is supposed to be an implicit type. In a sense, `A` has already been declared at the front of the signature by stipulating that it belongs to `Ord`. So writing:
```
sort : {A : Type} -> {{Ord A}} -> List A -> List A;
```
is more of information duplication than if the `Ord` wasn't there at the front.

So a fourth option is to think of a syntax that allows to merge `{A : Type} -> {{Ord A}}` into a single declaration and avoid the verbosity.

Like having some nice way to declare all prenex type variables and traits at the beginning of a signature in a succinct way. Our `{A B C : Type}` is already a bit verbose, because you need to keep typing this `Type` where it cannot be anything else.

**Comment by lukaszcz** [comment]
So in conclusion, I think maybe completely unrestricted generalisation is not a good idea, but inventing some special syntax for succinct declarations of prenex type variables and traits at the beginning of a type signature would be nice.

**Comment by lukaszcz** [comment]
How about e.g.:
```
{A {Ord A} {Eq A}}
```
for
```
{A : Type} -> {{Ord A}} -> {{Eq A}}
```
and
```
{A B C}
```
for 
```
{A B C : Type}
```
So you omit the `Type` and can just list all implicit type variables and traits.

But this works only at the beginning of the signature. The grammar for this would be something like:
```
<prenexDecl> ::= '{' <prenexDeclList> '}'
<prenexDeclList> ::= (<identifier> | <traitDecl>) <space> <prenexDeclList>?
<traitDecl> ::= '{' <expression> '}'
```
So it's easily distinguished from an ordinary type declaration with minimum backtracking.

There is ambiguity with `{Nat}`, but that's a problem only with dependent types and one can let the prenex declarations take priority and disambiguate with `{_ : Nat}` if necessary.

**Comment by lukaszcz** [comment]
Maybe actually
```
{{Ord A} {Eq A}}
```
would be better with implicit generalisation over `A`. Then this would be the only place where implicit generalisation happens.

**Comment by lukaszcz** [comment]
Yes, this forall syntax looks nice. I would just replace the forall with some non-unicode symbol or some brackets.

**Comment by janmasrovira** [comment]
sure, you can use `forall` instead, as in haskell

**Comment by lukaszcz** [comment]
I don't like `forall` because it's too long for something that gets used extremely often. That's one of the things that annoy me in Coq -- the verbosity of writing `forall` all the time. In Haskell it's less annoying only because you typically omit it for small signatures. This is not succinct.

I would advocate either for some kind of parentheses (like proposed above) or something shorter at the front. I propose `!`:
```
! A {B} {{Ord A}} ->
```
It's short and `forall` is often associated with `!` when rendered into ASCII. It doesn't need to get reserved, because we check it only at the beginning of the signature (only restriction: one can't put types named `!` at the front without parentheses).

**Comment by lukaszcz** [comment]
But I still think that the idea with braces at the front and implicit generalisation restricted to the traits inside nested braces is a bit better. Because the two most common use cases are:
```
{A B C} ->
```
and
```
{{Ord A} {Enum A}} ->
```
With "forall" syntax they are a bit less succinct (you need to repeat the braces):
```
! {A} {B} {C} ->
```
and
```
! {A} {{Ord A}} {{Enum A}} ->
```

**Comment by janmasrovira** [comment]
1. About `{A B C} -> `. This limits the use of this syntax to implicit arguments, right? With the `forall/!` alternative we don't have this limitation.
2. > With "forall" syntax they are a bit less succinct (you need to repeat the braces):
   ```
   ! {A} {B} {C} ->
   ```
   This is not the case. You can write `! {A B C} ->`
   
   ```
   ! {A} {{Ord A}} {{Enum A}} ->
   ```
   In this case, yes. But I don't think it is that bad. Maybe there could be sugar for grouping instance arguments `{{Ord A; Enum A}}`, but that's a different discussion. 
4. About generalising only inside of instance arguments, i.e. `{{Ord A} {Enum A}}`. I would find it very confusing if scoping rules were different inside instance arguments. Moreover, since we want short ways for defining type variables in general, I don't think we need to have special cases for instance arguments.
5. About this:
   > It doesn't need to get reserved, because we check it only at the beginning of the signature (only restriction: one can't put types named ! at the front without parentheses).
    
   I am not convinced by the idea of having special syntax for type signatures. If we were to support `forall/!`, it should be syntax supported in every expression. I'd would feel limiting and confusing to support this only at the beginning of a type signature and not in nested expressions, even if having it at the beginning is the most common. Therefore we would need to reserve `forall/!`. Noted that supporting this syntax in nested expressions is already relevant since we support higher rank functions.
6. About this
   >  True, but I don't think this matters that much (as long as you don't have dependent types), because all free variables 
   are type variables.

   We don't need full dependent types for this to matter. We can have variables of type `Type -> Type`, etc.
 
In my opinion, the Agda solution (`forall/!`) is better because:
1. It is succinct enough.
2. Works for both explicit and implicit arguments.
3. Is expression syntax, not type signature syntax.
4. Proven to work with dependent types.

**Comment by lukaszcz** [comment]
Yes, I agree forall/! is more general, and the succinctness difference is not big.

Maybe we should combine this with grouping. Since we already have
```
{A B C : Type} ->
```
we could allow
```
! {A B C} ->
```
and group traits as you suggested
```
! {A} {{Ord A; Enum A}} ->
```

**Comment by lukaszcz** [comment]
As a side note: Lean 4 has automatic type variable generalisation, but it avoids most problems with it by allowing it only for single lowercase or greek letters which are type variables by convention.

https://leanprover.github.io/lean4/doc/autobound.html

**Comment by lukaszcz** [comment]
Actually, we got a bit confused here, because the traits are type, so we want them on the right side of !, but we could still group them:
```
! {A B C} -> {{Ord A; Num B}} ->
```

**Comment by janmasrovira** [comment]
Ah, yes. I'm used to the Agda syntax, which allows to omit the arrow symbol when there is no ambiguity. E.g. the following is allowed.
```
(F : Type -> Type) (A : Type) -> F A; -- equivalent to
(F : Type -> Type) -> (A : Type) -> F A; 

-- And also:
∀ A B {C D E} {F} {G} (x : A) (y z : B) -> Nat; -- equivalent to
∀ (A : _) (B : _) {C D E : _} {F : _} {G : _} (x : A) (y z : B) -> Nat;  
-- note that `C D E` must of the same type since they share the hole
```
The option to omit `->` is very nice for succintness, but I remember that it was a bit confusing for me at first.

If we wanted to have this, then we could simply write:
```
! {A B C} {{Ord A; Num B}} ->
```
As stated before

**Comment by paulcadman** [comment]
This was discussed before we added succinct syntax for introducing type variables on the left of the `:`. We now think that the syntax is succinct enough.
