### ISSUE TITLE
High-level language syntax & semantics

### ISSUE THREAD

**Issue by cwgoes** [anoma/juvix#4]
This decision can mostly be delayed until later, and I don't think it's that important. The high-level language is just a set of syntax sugars and terse representations which will be rewritten to Juvix Core.

Probably quite similar to Idris (which in turn is quite similar to Haskell).

An interesting alternative would be to consider a Lisp-like syntax, although we'd have to figure out an idiomatic way of representing types.

**Comment by mariari** [comment]
Initial ideas on syntax

### Arrows

- Arrow syntax is relatively simple

- Without sugar all arrows will look like

```idris
 f : (x : Int) -1-> (y : Int) -w-> C -(x+y)-> D
```
- 
  + Note ∷ In the unicode extension ω can replace w
  + Note ∷  the last arrow requires dependent useages

- With sugar it would look something like this
```idris
f : (x : Int) -o (y : Int) -> C -(x+y)-> D
```
-
  + We can see that -o stands for 1 useage, and -> stands for unlimited useages
  + Note ∷ In the unicode extension → can replace ->
  + Note ∷ In the unicode extension  ⊸ can replace -o

### Stand alone useages

Due to arrows being only applicable with bindings, we can not determine the useage of the following

```idris
f : A
```

Thus we may want a way to quantify the useage of variables without arrows.

The following ideas were thought of

```idris
f 2 : A

f : A ~2 
f : ~2 A
```
-
  + The first idea was rejected because it is ambiguous in some situations
  + I also don't fully like the second, as how does this work with named arguments? It seems like arbitrary extra syntax  

### Additive conjunction

- The literature uses `&` for this, however to be less confusing for the user I suggest this

```idris
Data A : Set where
  | F : X \/ Y -o A

f : (x : A) -o X
f x = (_1 x) 
```
- 
  + Note ∷ _1 is a placeholder for a better name of accessing the first variant without being able to inspect on the second
  + Note ∷ in the unicode extension ∨ can replace `\/`

**Comment by cwgoes** [comment]
@mariari I think we should close this in favour of #273, but is there any of this syntax brainstorming that you want to port to the design documentation in `docs` first?

**Comment by mariari** [comment]
The only comment which hasn't been ported yet is the lisp syntax discussion. I will add that to docs in a new PR
