### ISSUE TITLE
Increase publications and improve documentation to engage the community

### ISSUE THREAD

**Issue by thealmarty** [anoma/juvix#494]
Idris and Idris 2 have successfully engage a relatively large community for a dependently typed language. I notice a few actions that may have caused the success:

- make it very easy for the community to contribute. They do so by maintaining good documentation and making implementation decisions that make it easy to contribute (e.g., as mentioned in the interactive development environment issue).
- engage audiences through different channels. For example, blog posts may appeal to developers while working/published academic paper may appeal to academic researchers.

Juvix can follow Idris's suit and engage a large community by various channels:

- present the implementation of the language in detail in various events. Similar to the [SPLV2020 lectures](https://www.youtube.com/playlist?list=PLmYPUe8PWHKqBRJfwBr4qga7WIs7r60Ql)
- maintain a friendly and detailed implementation documentation page similar to [Idris 2's](https://idris2.readthedocs.io/en/latest/implementation/index.html). (@mariari)
- publish a working paper detailing the implementation, similar to [this](https://www.type-driven.org.uk/edwinb/papers/idris2.pdf). (@cwgoes perhaps the stripped version of the language ref is a good starting point?)
- publish blog posts (already planned).

**Comment by mariari** [comment]
When we push Juvix, we'll also need some kind of support channel to help others and encourage the community to help others.

This will likely take the form of IRC and or a discord server.

Further a forum for longer form user discussion will also be wanted.

**Comment by LoPoHa** [comment]
An opinion from a beginner (not 100% on topic though):

Idris was my first and only dependently typed language. In fact it was my first functional language at all. 
But the book by edwin brady made the on boarding simple.
The type driven development with synthesis and hole inspection(?) was also helpful, because the compiler really felt like an assistant and not like something that is between you and a working program. (#493)
And it was one of the things that made the language appealing from the outside (at least for me).
So having a book like tutorial would be great.
Especially one that is not only focused on proofing things, but also (or even more) on programming.
Maybe combining a few of the blog posts you have written gives a good start?

I also don't understand the scope of this language.
The 1.0 release will be Tezos only.
And the 1.1 release will contain a llvm backend, but "smart contract" is written all over the place (a small exaggeration)
So will i be able to write e.g. a webserver, make juvix self-hosting or a package manager? (ignoring the lack of libraries)
The llvm backend implies it is?
Since i'm not interested in smart contracts, i'll wait for the 1.1 release and hope it will be general purpose 😄 
Nonetheless i wish you good look with the language!

PS: I'm sure you selected the license with to match your requirements, but having the standard lib licensed under gpl3 will be a though sell imo. Would it be possible to license it under something like mit/bsd/apache. (Note: i'm not talking about the compiler!)
I can't find a package manager (yet, but having something like cargo for example would be nice), so swapping the stdlib to something else (that gets used by other projects to have some kind of network effects) would be unnecessarily hard.
And if i understand the gpl3 correctly (ianal), this would require to have every source of juvix be licensed under it if you don't want to ship the standard library as a dll/so. (Not sure if this even possible on smart contracts_

**Comment by cwgoes** [comment]
We should do this but this issue is too out-of-date.
