### ISSUE TITLE
Golden: To Compact or not to Compact

### ISSUE THREAD

**Issue by mariari** [anoma/juvix#855]
With the PR #823 we have two different formatting styles for golden files. One with Compact ()'s and one without. We use the compact version for s-expressions so we don't end up with

```
( ":defun" ....
        ( "form" )
      )
    )
  )
)
```

However this begs the question is it always clearer to have parens hug, or should we leave it like this for files like?

Non Compact Example:
https://github.com/anomanetwork/juvix/blob/develop/test/examples-golden/positive/llvm/Const/Const.parsed

Compact Example:
https://github.com/anomanetwork/juvix/blob/ae2208860636ff0606ecae577d182241c0870b17/test/examples-golden/positive/llvm/Const/Const.parsed

**Comment by rokopt** [comment]
My first, reflex reaction is that my main use of these files will be diffing expected versus actual results, so I'd want whatever would produce the cleanest diff output, if either.  And I think that the non-compact version would produce more readable `diff -w` output in some cases, if there's a missing or extra level of nesting?

That also makes me wonder whether something like https://github.com/stamourv/sexp-diff or https://fosdem.org/2021/schedule/event/sexpressiondiff/ would work on our format, or if it could be easily adapted so that one of those tools would.

**Comment by systemf-frank** [comment]
I agree with @rokopt, diffing will be more straightforward with the longer style, which could be really handy.

**Comment by cwgoes** [comment]
Done.
